### ISSUE TITLE
Forgot Password backend code

### ISSUE THREAD

**Issue by Apeksha-P** [Apeksha-P/AI-Based-Water-Management-System#121]
AI-Based Water Management System Issue Template
-
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**Our project aims to leverage artificial intelligence (AI) technologies to optimize water resource management, predict usage patterns, and improve overall efficiency.**

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Below, you'll find the template to create tasks related to the development of our project.

**Description:**
Creating a login feature with a forgot password functionality.

**Expected Behavior:**
Once the task is completed, users should be able to log in to the system securely. Additionally, they should have the option to reset their password if forgotten.

**Steps to Reproduce:**
Create a login page UI with fields for username/email and password.
Implement backend logic to handle forgot password requests, including generating and sending password reset emails.
Create a password reset page UI with a form for users to enter their new password.
Implement backend logic to verify and update the user's password.

**Additional Information:**
It's essential to ensure password security by using encryption and secure password storage techniques.

**Comment by kvabhaya** [comment]
done
