### ISSUE TITLE
Edit profile details except for the email

### ISSUE THREAD

**Issue by Apeksha-P** [Apeksha-P/AI-Based-Water-Management-System#133]
AI-Based Water Management System Issue Template
-
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**Our project aims to leverage artificial intelligence (AI) technologies to optimize water resource management, predict usage patterns, and improve overall efficiency.**

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Below, you'll find the template to create tasks related to the development of our project.

**Description:**
Edit profile details except for the email

**Comment by YasinsaMahanama** [comment]
Done
