### ISSUE TITLE
Design and implement a template for sending OTP emails

### ISSUE THREAD

**Issue by Apeksha-P** [Apeksha-P/AI-Based-Water-Management-System#135]
AI-Based Water Management System Issue Template
-
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**Our project aims to leverage artificial intelligence (AI) technologies to optimize water resource management, predict usage patterns, and improve overall efficiency.**

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Below, you'll find the template to create tasks related to the development of our project.

**Description:**
Design and implement a template for sending OTP emails to users for authentication and verification purposes.

**Expected Behavior:**
Once completed, users should receive an email containing a dynamically generated OTP that they can use for authentication or verification purposes.

**Steps to Reproduce:**
Design an email template with placeholders for the OTP code and instructions for the user.
Implement a mechanism to generate a unique OTP code for each email request.
Integrate the email template with the project's email sending functionality.
Test the email sending process to ensure that users receive the OTP emails promptly and accurately.

**Additional Information:**
Ensure that the email template is visually appealing and includes clear instructions for the user.
Provide fallback options for users who may not receive the OTP email immediately.

**Labels:**
Email, authentication, enhancement

**Due Date:**
Before 24-04-2024 10.00 a.m.

**Comment by kvabhaya** [comment]
Done
